export const Icons = {
  leftArrow: require('./leftArrow.png'),
  bell: require('./bell.png'),
  greenwhitebulb: require('./greenwhitebulb.png'),
  tvorange: require('./tvorange.png'),
  tvblue: require('./tvblue.png'),
  chevronforward: require('./chevron_forward.png'),
  wallet: require('./wallet.png'),
  locker: require('./locker.png'),
  bookmarkblue: require('./bookmarkblue.png'),
  unpaidstatus: require('./unpaidstatus.png'),
  paymentaccount: require('./paymentaccount.png'),
  verticalline: require('./verticalline.png'),
  chevrondown: require('./chevron-down.png'),
  phonecode: require('./phonecode.png'),
  signin: require('./signin.png'),
  personal: require('./personal.png'),
  addcircle: require('./add_circled.png'),
  nobill: require('./nobill.png'),
};
